### ISSUE TITLE
Mad Science Friday #1 - 24/11/2017

### ISSUE THREAD

**Issue by tsirlucas** [Beakyn/awesome-beakyn#1]
### Hello world!

In our first Creative Friday, everyone be in charge of creating a project/research about some technology and prove a point like how it can bring value to the company and/or to another projects.

The way it goes is simple, first of all you have to create a new issue with the **creative fridays** label and comment this issue with the #hash for your own, linking both.

Your issue will have to use the following template and be assigned to yourself.

> **What's your project/research?** 
> A nice project name
> 
> **Describe your project/research**
> Well I don't think I have to explain it...
> 
> **What's your goal?**
> A reason why you're doing this

After that, you'll work on your project and then create a PR adding your issue link to the readme (Remember to close it with the #hash) with the **creative fridays** label answering the following questions:

> **What's your project/research?** 
> A nice project name
> 
> **Describe your project/research**
> Well I don't think I have to explain it...
> 
> **Link your repo**
> URL for your Github repo
> 
> **What's your goal?**
> A reason why you're doing this
> 
> **Have you accomplished it??**
> Yes/No
> 
> **If don't, why?**
> Answer or [ANSWER ON MEDIUM POST]
> 
> **What have you learned?**
> Answer or [ANSWER ON MEDIUM POST]
> 
> **Anything that you would like to add**
> Answer or [N/A]
> 
> **Any idea for the next Creative Friday?**
> Answer or [N/A]

By the end of the event, we will create a Milestone with all the issues and PRs.

**Comment by tsirlucas** [comment]
Adding Web Assembly Research #2

**Comment by nelsoneldoro** [comment]
Adding Testing React components and Redux-Sagas #3

**Comment by ythecombinator** [comment]
Added *Decentralized-technologies-based stack research* #4

**Comment by tsirlucas** [comment]
Adding Typefy ElasaticLunr #5
