### ISSUE TITLE
Web Assembly Research

### ISSUE THREAD

**Issue by tsirlucas** [Beakyn/awesome-beakyn#2]
**What's your project/research?**
Web Assembly Research

**Describe your project/research**
I will make a research about the use of Web Assembly with expensive algorithms on languages like C, including a benchmark versus vanilla.js. The main point is also to know how the browser will behave with features that we don't have natively in Javascript like lazy evaluation. 

**What's your goal?**
Answer why isn't everyone using Web Assembly yet and take down some doubts about its limitations and speed. (This knowledge can be very useful on future projects/features/improvements)

**Comment by juanpujol** [comment]
@tsirlucas this is the post I mentioned: https://blog.figma.com/webassembly-cut-figmas-load-time-by-3x-76f3f2395164
